# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Jessica McGillen
description:      'A researcher at the interface between disease modelling and global health policy.'
url:              http://jessicamcgillen.com
baseurl:          /

author:
  name:           'Jessica McGillen'
  url:            https://twitter.com/jbmcgillen

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jessicamcgillen/website

gems: [jekyll-paginate]

twitter_username: jbmcgillen